### ISSUE TITLE
Add support for code in title

### ISSUE THREAD

**Issue by keaising** [qqhann/hugo-primer#27]
Hello Pan,

When I use code in title, for example:

![图片](https://user-images.githubusercontent.com/8179012/57576694-f8d3ec80-7498-11e9-8d5e-66d02137270c.png)

the result of TOC is broken into three lines, like this:

![图片](https://user-images.githubusercontent.com/8179012/57576701-215be680-7499-11e9-81c8-bfba04a7d1d8.png)

I try to fix it but I cannot find out where should I modify.

All of us will appreciate it if you can fix it.

如果我的英语没有太讲明白的话，问题是这样的：

在标题里插入代码会造成右上角生成的目录里，插入代码了的那行标题会折成多行。

不知道是bug还是feature，如果是bug的话麻烦修复，非常感谢！

**Comment by qqhann** [comment]
Hello Wang,

Thanks for opening the issue.
This problems seems to be caused by `code` tag included in the TOC generated by hugo's `{{ .TableOfContents }}`.
I couldn't fix it by editing `code` tag's CSS.

I'm considering stop using default `{{ .TableOfContents }}` as a workaround.
https://github.com/gohugoio/hugo/issues/1778
I'll work on it when I have time. :)

**Comment by andreyorst** [comment]
I've kinda solved this issue with TOC by changing styles a bit:

```css
#toc {
  margin-top: 1.5rem;
  padding: 0.7rem;
  text-overflow: ellipsis;
  overflow: hidden;
}
#toc * {
  list-style: none;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
```

WIth these changes TOC looks like this:
![image](https://user-images.githubusercontent.com/19470159/78545823-1aeb0180-7805-11ea-9fbb-d1cfb3b30df9.png)

I'm not sure if it is ok for everyone, but I'm ok with truncated headings.
